apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: human-resources-fxfx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: human-resources-fxfx
    app.kubernetes.io/part-of: test-output-app
  name: human-resources-fxfx
  namespace: jephilli-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: human-resources-fxfx
    weight: null
status: {}
